---
title: "Topographic Data in R"
author: "Eric Pante, Benoit Simon-Bouhet and Jean-Olivier Irisson"
output: html_notebook
params:
  dataset: "florida"
---

marmap is a package designed for downloading, plotting and manipulating bathymetric and topographic data in R.

```{r setup}
library(marmap, warn = FALSE)
library(ggplot2, warn = FALSE)
library(viridis, warn = FALSE)

data(list = params$data)
df <- fortify(get(params$data))

p <- ggplot(df, aes(x=x, y=y)) +
  geom_raster(aes(fill=z)) +
  geom_contour(aes(z=z), colour="white", size=0.1,
    breaks=c(-100, -200, -500, -1000, -2000, -4000)) + 
  geom_contour(aes(z=z), colour="white", size=0.3, breaks=0) + 
  theme_void() + 
  coord_fixed()
```

## Using Topographic Colors

```{r}
p +  scale_fill_etopo()
```

## Using Viridis Colors

```{r}
p +  scale_fill_viridis()
```

## Using Bash

You can also embed code from other languages, such as **bash**:

```{bash}
cat flights1.csv flights2.csv flights3.csv > flights.csv
ls [f]*
```

## Using Python

Or **python**:

```{python}
import pandas

# Read flights data and select flights to O'Hare
flights = pandas.read_csv("flights.csv", low_memory=False)
flights = flights[flights['dest'] == "MCO"]

# Select carrier and delay columns and drop rows with missing values
flights = flights[['carrier', 'dep_delay', 'arr_delay']]
flights = flights.dropna()
print flights.head(10)
flights.to_csv("mco.csv")
```
